plugins {
    id 'java'
    id 'application'
}

application {
    mainClass.set("Application")
}

group = 'com.up202205324.hero'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation group: 'com.googlecode.lanterna', name: 'lanterna', version: '3.1.1'
}

test {
    useJUnitPlatform()
}

